---
# ROLE: ruby
# roles/ruby/tasks/main.yml
#
# removes package ruby, installs ruby from source
#
#- name: check ruby {{ ruby_version }} installed
#  shell: "ruby -v | grep {{ ruby_version }}"
#  register: ruby_installed
#  changed_when: false
#  ignore_errors: yes # failure means our ruby version isn't installed yet
#  always_run: yes

- name: remove package ruby
  become: yes
  package: name=ruby state=absent

- name: download ruby
  become: yes
  get_url: url={{ ruby_gzip_url }} sha256sum={{ ruby_sha_256 }} owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} dest={{ install_path }}/ruby-{{ ruby_ver }}.tar.gz
  
- name: unzip ruby file
  become: yes
  unarchive: src=/opt/install/ruby-{{ ruby_ver }}.tar.gz dest={{ install_path }}/ creates={{ install_path }}/ruby-{{ ruby_ver }}/compile.c copy=no

- name: check if ruby is installed
  become: yes
  stat: path=/usr/local/bin/ruby
  register: ruby

- name: configure ruby
  become: yes
  shell: cd {{ install_path }}/ruby-{{ ruby_ver }} && ./configure --enable-shared creates={{ install_path }}/ruby-{{ ruby_ver }}/Makefile
  
- name: make ruby
  become: yes
  shell: cd {{ install_path }}/ruby-{{ ruby_ver }} && make 
  when: ruby.stat.exists == False

- name: install ruby
  become: yes
  shell: cd {{ install_path }}/ruby-{{ ruby_ver }} && make install creates=/usr/local/bin/ruby
  when: ruby.stat.exists == False

- name: update rubygems
  become: yes
  command: gem update --system
 
- name: install bundler
  become: yes
  gem: name=bundler user_install=no state=present
